version: "3.8"

services:
  # --- BASES DE DONNÃ‰ES ---
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: eSantePg
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init/pg_init.sql:/docker-entrypoint-initdb.d/pg_init.sql

  influxdb:
    image: influxdb:2.7
    container_name: influx_db
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb2
      - ./init/influx_init.sh:/docker-entrypoint-initdb.d/influx_init.sh
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: eSanteIdb
      DOCKER_INFLUXDB_INIT_BUCKET: mesure_data

  # --- MICRO-SERVICES ---
  monitoring-service:
    build: ./backend/monitoring-service
    container_name: monitoring_service
    restart: always
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/eSantePg
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_INFLUX_URL: http://influxdb:8086
      SPRING_INFLUX_ORG: eSanteIdb
      SPRING_INFLUX_BUCKET: mesure_data
      SPRING_INFLUX_TOKEN: admin123
    depends_on:
      - postgres
      - influxdb

  reporting-service:
    build: ./backend/reporting-service
    container_name: reporting_service
    restart: always
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/eSantePg
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres

  notification-service:
    build: ./backend/notification-service
    container_name: notification_service
    restart: always
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:notifications;DB_CLOSE_DELAY=-1
    depends_on:
      - postgres
